project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
website:
  title: "Data Science Project #1: Baseball Statistics"
  favicon: Images/Baseball.png
  navbar:
    left:
      - href: /
        text: Overview
      - href: About_Me.qmd
        text: About
      - text: Workflow
        menu:
          - text: Data Collection
            href: Workflow/Data_Collection.ipynb
          - text: Data Cleaning
            href: Workflow/Data_Cleaning.ipynb
          - text: EDA
            href: Workflow/EDA.ipynb
          - text: Supervised Learning
            href: Workflow/Supervised_Learning.ipynb
          - text: Unsupervised Learning
            href: Workflow/Unsupervised_Learning.ipynb
format:
  html:
    theme: cerulean
    toc: true