project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
website:
  title: DSAN-5000 Project
  favicon: Assets/GU_Logo.png
  navbar:
    left:
      - href: /
        text: Home Page
      - href: About_Me.qmd
        text: About Me
      - href: Report.qmd
        text: Report
      - text: Technical Details
        menu:
          - text: Data Collection
            href: Technical_Details/Data_Collection.ipynb
          - text: Data Cleaning
            href: Technical_Details/Data_Cleaning.ipynb
          - text: EDA
            href: Technical_Details/EDA.ipynb
          - text: Supervised Learning
            href: Technical_Details/Supervised_Learning.ipynb
          - text: Unsupervised Learning
            href: Technical_Details/Unsupervised_Learning.ipynb
          - text: LLM Usage Log
            href: Technical_Details/LLM_Usage_Log.qmd
bibliography: Assets/References.bib
format:
  html:
    theme: cosmo
    toc: true