project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
website:
  title: "Data Science Project: Baseball Statistics"
  favicon: Images/Baseball.png
  navbar:
    left:
      - href: /
        text: Overview
      - href: About.qmd
        text: About
      - text: Lifecycle
        menu:
          - text: Data Collection
            href: Lifecycle/Data_Collection.ipynb
          - text: Data Cleaning
            href: Lifecycle/Data_Cleaning.ipynb
          - text: EDA
            href: Lifecycle/EDA.ipynb
          - text: Supervised Learning
            href: Lifecycle/Supervised_Learning.ipynb
          - text: Unsupervised Learning
            href: Lifecycle/Unsupervised_Learning.ipynb
format:
  html:
    theme: cerulean
    toc: true