---
title: LLM Usage Log
---

## Brainstorming

- I had ChatGPT help me find relevant data through `pybaseball`. That is, I asked ChatGPT what `pybaseball` *functions* I should use, etc. and it gave me a rundown of the use cases, similar to what I include in `Data_Collection.ipynb`.

## Writing

- I used ChatGPT to help me revise *text* in `About_Me.qmd`.
- I used ChatGPT to help me revise *text* in `Data_Collection.ipynb`.
- I used ChatGPT to help me revise *text* in `Data_Cleaning.ipynb`.
- I used ChatGPT to help me revise *text* in `EDA.ipynb`.
- I used ChatGPT AND Claude to help me revise *text* in `Supervised_Learning.ipynb`. I used Claude specifically for mathematical content.
- I used ChatGPT to help me revise *text* in `Unsupervised_Learning.ipynb`.
- I used ChatGPT to help me revise *text* in `Report.qmd` and `index.qmd`.

## Coding

- I used ChatGPT to help me write the code for the linear *regression* and logistic *classifier* tasks in `Supervised_Learning.ipynb`, just to save some time. 
    - That is, I am not as familiar with `sklearn` as I probably should be as of 1/2026. This is a work in progress for me. The same goes for the code required to do K-means, etc. in `Unsupervised_Learning.ipynb`. At this point, I am more drawn to the *math behind these basic algorithms* (given my undergraduate major) than I am the coding aspect, hence why I include a good deal of math in the modeling notebooks, specifically the derivation when I introduce the logistic classifier.